require "perpluginconfig.treesitter"
require "perpluginconfig.base16"
require "perpluginconfig.telescope_file_browser"
require "perpluginconfig.telescope"
require "perpluginconfig.colorizer"
require "perpluginconfig.devicons"
require "perpluginconfig.substitute"
require "perpluginconfig.leap"
require "perpluginconfig.gitsigns"
require "perpluginconfig.todocomments"
require "perpluginconfig.cmp"

